Some updates

diff --git a/src/scripts/jnt_lapinoo.init b/src/scripts/jnt_lapinoo.init
--- a/src/scripts/jnt_lapinoo.init
+++ b/src/scripts/jnt_lapinoo.init
@@ -1,61 +1,74 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:     jnt_lapinoo
-# Required-Start:   $remote_fs $syslog $network
-# Required-Stop:    $remote_fs $syslog $network
-# Default-Start:    2 3 4 5
-# Default-Stop:     0 1 6
+# Provides:             jnt_lapinoo
+# Required-Start:       $remote_fs $syslog $network
+# Required-Stop:        $remote_fs $syslog $network
+# Default-Start:        2 3 4 5
+# Default-Stop:         0 1 6
 # Short-Description:    Janitoo lapinoo
-# Description:      Janitoo lapinoo appliance server
+# Description:          Janitoo lapinoo appliance server
 #
 ### END INIT INFO
 
+NAME="jnt_lapinoo"
+
+# Internal script
+# You should not update lines below
+# Version 0.0.7
 set -e
 
-NAME="jnt_lapinoo"
 DAEMON="/usr/bin/${NAME}"
+test -x "${DAEMON}" || DAEMON="/usr/sbin/${NAME}"
 test -x "${DAEMON}" || DAEMON="/usr/local/bin/${NAME}"
-PATH="/sbin:/bin:/usr/sbin:/usr/bin"
-CONFFILE="/opt/janitoo/etc/janitoo_lapinoo.conf"
 
-test -x "${DAEMON}" || exit 0
+CONFFILE="/etc/janitoo/${NAME}.conf"
+test -f "${CONFFILE}" || CONFFILE="/opt/janitoo/etc/${NAME}.conf"
+
+test -x "${DAEMON}" || echo "Can't find ${DAEMON}" && exit 0
+test -f "${CONFFILE}" || echo "Can't find ${CONFFILE}" && exit 0
+
+PATH="/sbin:/bin:/usr/sbin:/usr/bin"
+
+PIDFILE="/opt/janitoo/run/${NAME}.pid"
+test -d "/run/janitoo" && PIDFILE="/run/janitoo/${NAME}.pid"
+test -d "/var/run/janitoo" && PIDFILE="/var/run/janitoo/${NAME}.pid"
 
 case "${1}" in
     start)
-        echo -n "Starting Janitoo lapinoo server: "
+        echo -n "Starting ${NAME} server: "
         ${DAEMON} -c ${CONFFILE} start
         echo "${NAME}."
         ;;
 
     stop)
-        echo -n "Stopping Janitoo lapinoo server: "
+        echo -n "Stopping ${NAME} server: "
         ${DAEMON} -c ${CONFFILE} stop
         echo "${NAME}."
         ;;
 
     restart)
-        echo -n "Restarting Janitoo lapinoo server: "
+        echo -n "Restarting ${NAME} server: "
         ${DAEMON} -c ${CONFFILE} restart
         echo "${NAME}."
         ;;
 
     reload|force-reload)
-        echo -n "Reloading Janitoo lapinoo server: "
+        echo -n "Reloading ${NAME} server: "
         ${DAEMON} -c ${CONFFILE} reload
         echo "${NAME}."
         ;;
 
     kill)
-        echo -n "Kill Janitoo lapinoo server: "
+        echo -n "Kill Janitoo fishtank server: "
         ${DAEMON} -c ${CONFFILE} kill
         echo "${NAME}."
         ;;
 
     status)
-        PID="$(cat /opt/janitoo/run/${NAME}.pid 2>/dev/null)" || true
+        PID="$(cat ${PIDFILE} 2>/dev/null)" || true
 
-        if [ ! -f /opt/janitoo/run/${NAME}.pid ] || [ -z "${PID}" ]
+        if [ ! -f ${PIDFILE} ] || [ -z "${PID}" ]
         then
             echo "${NAME} is not running"
             exit 3
